### ISSUE TITLE
投稿画面から録音画面に戻ってくると、フォーカスが当たらない

### ISSUE THREAD

**Issue by WakeNaoki** [inai17ibar/sight_on_ios#5]

**Comment by WakeNaoki** [comment]
ボイスオーバー中かどうかを判定する
if(UIAccessibilityIsVoiceOverRunning()){
    //ボイスオーバー中
}else{
 
}

**Comment by inai17ibar** [comment]
ページビューコントローラ方式からタブバー方式に変更した。またレイアウトを整えて、画面遷移のタイミングでフォーカスがロストしないようにした。
